#!/usr/bin/env node
/**
 * Single source of truth for release identity, shared by Web and iOS.
 *
 *   version      -> package.json "version"        (marketing version, e.g. 1.0.0)
 *   buildNumber  -> git commit count on HEAD      (monotonic, same for Web + iOS)
 *   commit       -> short git sha
 *   builtAt      -> ISO timestamp of the build
 *
 * Outputs (both generated, never hand-edited):
 *   src/lib/build-info.generated.ts   consumed by the web + native bundles
 *   native/ios/version.xcconfig       consumed by Xcode (MARKETING_VERSION / CURRENT_PROJECT_VERSION)
 *
 * Usage:
 *   node scripts/version.mjs           # write both outputs
 *   node scripts/version.mjs --check   # verify outputs are in sync (CI), exit 1 if not
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");

const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const version = pkg.version;
if (!/^\d+\.\d+\.\d+$/.test(version ?? "")) {
  console.error(`[version] package.json "version" must be x.y.z, got: ${version}`);
  process.exit(1);
}

function git(cmd, fallback) {
  try {
    return execSync(`git ${cmd}`, { cwd: root, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

// CI overrides win so a re-run of the same commit can bump the build number.
const buildNumber = Number(process.env.BUILD_NUMBER ?? git("rev-list --count HEAD", "1")) || 1;
const commit = process.env.GIT_COMMIT_SHA?.slice(0, 7) ?? git("rev-parse --short HEAD", "unknown");
const releaseId = `${version}+${buildNumber}.${commit}`;

const tsPath = join(root, "src", "lib", "build-info.generated.ts");
const xcPath = join(root, "native", "ios", "version.xcconfig");

const tsBody = `// GENERATED by scripts/version.mjs — do not edit by hand.
// Run \`bun run version:sync\` to refresh.
export const BUILD_INFO = {
  /** Marketing version, mirrors package.json and iOS MARKETING_VERSION. */
  version: "${version}",
  /** Monotonic build number, mirrors iOS CURRENT_PROJECT_VERSION. */
  buildNumber: ${buildNumber},
  /** Short git sha the bundle was built from. */
  commit: "${commit}",
  /** Traceable release id shared by Web and iOS. */
  releaseId: "${releaseId}",
} as const;

export type BuildInfo = typeof BUILD_INFO;
`;

const xcBody = `// GENERATED by scripts/version.mjs — do not edit by hand.
// Run \`bun run version:sync\` to refresh. Keep in sync with src/lib/build-info.generated.ts.
MARKETING_VERSION = ${version}
CURRENT_PROJECT_VERSION = ${buildNumber}
MAITRI_GIT_COMMIT = ${commit}
MAITRI_RELEASE_ID = ${releaseId}
`;

if (check) {
  const problems = [];
  for (const [path, expected] of [
    [tsPath, tsBody],
    [xcPath, xcBody],
  ]) {
    if (!existsSync(path)) {
      problems.push(`missing ${path}`);
      continue;
    }
    // builtAt is intentionally absent so the outputs are byte-stable per commit.
    if (readFileSync(path, "utf8") !== expected) problems.push(`out of date: ${path}`);
  }
  if (problems.length) {
    console.error(`[version] release metadata is not in sync:\n  - ${problems.join("\n  - ")}`);
    console.error(`[version] run \`bun run version:sync\` and commit the result.`);
    process.exit(1);
  }
  console.log(`[version] in sync — ${releaseId}`);
  process.exit(0);
}

writeFileSync(tsPath, tsBody);
writeFileSync(xcPath, xcBody);
console.log(`[version] ${releaseId}`);
console.log(`[version] wrote src/lib/build-info.generated.ts + native/ios/version.xcconfig`);
