// GENERATED by scripts/version.mjs — do not edit by hand.
// Run `bun run version:sync` to refresh.
export const BUILD_INFO = {
  /** Marketing version, mirrors package.json and iOS MARKETING_VERSION. */
  version: "1.0.0",
  /** Monotonic build number, mirrors iOS CURRENT_PROJECT_VERSION. */
  buildNumber: 1364,
  /** Short git sha the bundle was built from. */
  commit: "0c724c3",
  /** Traceable release id shared by Web and iOS. */
  releaseId: "1.0.0+1364.0c724c3",
} as const;

export type BuildInfo = typeof BUILD_INFO;
