/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SideBySideRouteImport } from './routes/side-by-side'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchmakerRouteImport } from './routes/matchmaker'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const SideBySideRoute = SideBySideRouteImport.update({
  id: '/side-by-side',
  path: '/side-by-side',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakerRoute = MatchmakerRouteImport.update({
  id: '/matchmaker',
  path: '/matchmaker',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/matchmaker': typeof MatchmakerRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sessions': typeof SessionsRoute
  '/side-by-side': typeof SideBySideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/matchmaker': typeof MatchmakerRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sessions': typeof SessionsRoute
  '/side-by-side': typeof SideBySideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/matchmaker': typeof MatchmakerRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sessions': typeof SessionsRoute
  '/side-by-side': typeof SideBySideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connections'
    | '/matchmaker'
    | '/profile'
    | '/reset-password'
    | '/sessions'
    | '/side-by-side'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connections'
    | '/matchmaker'
    | '/profile'
    | '/reset-password'
    | '/sessions'
    | '/side-by-side'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/connections'
    | '/matchmaker'
    | '/profile'
    | '/reset-password'
    | '/sessions'
    | '/side-by-side'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConnectionsRoute: typeof ConnectionsRoute
  MatchmakerRoute: typeof MatchmakerRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionsRoute: typeof SessionsRoute
  SideBySideRoute: typeof SideBySideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/side-by-side': {
      id: '/side-by-side'
      path: '/side-by-side'
      fullPath: '/side-by-side'
      preLoaderRoute: typeof SideBySideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaker': {
      id: '/matchmaker'
      path: '/matchmaker'
      fullPath: '/matchmaker'
      preLoaderRoute: typeof MatchmakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConnectionsRoute: ConnectionsRoute,
  MatchmakerRoute: MatchmakerRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionsRoute: SessionsRoute,
  SideBySideRoute: SideBySideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
