/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SideBySideRouteImport } from './routes/side-by-side'
import { Route as MatchmakerRouteImport } from './routes/matchmaker'
import { Route as CompassRouteImport } from './routes/compass'
import { Route as IndexRouteImport } from './routes/index'

const SideBySideRoute = SideBySideRouteImport.update({
  id: '/side-by-side',
  path: '/side-by-side',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakerRoute = MatchmakerRouteImport.update({
  id: '/matchmaker',
  path: '/matchmaker',
  getParentRoute: () => rootRouteImport,
} as any)
const CompassRoute = CompassRouteImport.update({
  id: '/compass',
  path: '/compass',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compass': typeof CompassRoute
  '/matchmaker': typeof MatchmakerRoute
  '/side-by-side': typeof SideBySideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compass': typeof CompassRoute
  '/matchmaker': typeof MatchmakerRoute
  '/side-by-side': typeof SideBySideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compass': typeof CompassRoute
  '/matchmaker': typeof MatchmakerRoute
  '/side-by-side': typeof SideBySideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compass' | '/matchmaker' | '/side-by-side'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compass' | '/matchmaker' | '/side-by-side'
  id: '__root__' | '/' | '/compass' | '/matchmaker' | '/side-by-side'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompassRoute: typeof CompassRoute
  MatchmakerRoute: typeof MatchmakerRoute
  SideBySideRoute: typeof SideBySideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/side-by-side': {
      id: '/side-by-side'
      path: '/side-by-side'
      fullPath: '/side-by-side'
      preLoaderRoute: typeof SideBySideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaker': {
      id: '/matchmaker'
      path: '/matchmaker'
      fullPath: '/matchmaker'
      preLoaderRoute: typeof MatchmakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compass': {
      id: '/compass'
      path: '/compass'
      fullPath: '/compass'
      preLoaderRoute: typeof CompassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompassRoute: CompassRoute,
  MatchmakerRoute: MatchmakerRoute,
  SideBySideRoute: SideBySideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
