#!/usr/bin/env node
/**
 * Single source of truth for release identity, shared by Web and iOS.
 *
 *   version      -> package.json "version"        (marketing version, e.g. 1.0.0)
 *   buildNumber  -> git commit count on HEAD      (monotonic, same for Web + iOS)
 *   commit       -> short git sha
 *   builtAt      -> ISO timestamp of the build
 *
 * Outputs (both generated, never hand-edited):
 *   src/lib/build-info.generated.ts   consumed by the web + native bundles
 *   native/ios/version.xcconfig       consumed by Xcode (MARKETING_VERSION / CURRENT_PROJECT_VERSION)
 *
 * Usage:
 *   node scripts/version.mjs           # write both outputs
 *   node scripts/version.mjs --check   # verify outputs are in sync (CI), exit 1 if not
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");

const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const version = pkg.version;
if (!/^\d+\.\d+\.\d+$/.test(version ?? "")) {
  console.error(`[version] package.json "version" must be x.y.z, got: ${version}`);
  process.exit(1);
}

function git(cmd, fallback) {
  try {
    return execSync(`git ${cmd}`, { cwd: root, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

// CI overrides win so a re-run of the same commit can bump the build number.
const buildNumber = Number(process.env.BUILD_NUMBER ?? git("rev-list --count HEAD", "1")) || 1;
const commit = process.env.GIT_COMMIT_SHA?.slice(0, 7) ?? git("rev-parse --short HEAD", "unknown");
const releaseId = `${version}+${buildNumber}.${commit}`;

const tsPath = join(root, "src", "lib", "build-info.generated.ts");
const xcPath = join(root, "native", "ios", "version.xcconfig");

const tsBody = `// GENERATED by scripts/version.mjs — do not edit by hand.
// Run \`bun run version:sync\` to refresh.
export const BUILD_INFO = {
  /** Marketing version, mirrors package.json and iOS MARKETING_VERSION. */
  version: "${version}",
  /** Monotonic build number, mirrors iOS CURRENT_PROJECT_VERSION. */
  buildNumber: ${buildNumber},
  /** Short git sha the bundle was built from. */
  commit: "${commit}",
  /** Traceable release id shared by Web and iOS. */
  releaseId: "${releaseId}",
} as const;

export type BuildInfo = typeof BUILD_INFO;
`;

const xcBody = `// GENERATED by scripts/version.mjs — do not edit by hand.
// Run \`bun run version:sync\` to refresh. Keep in sync with src/lib/build-info.generated.ts.
MARKETING_VERSION = ${version}
CURRENT_PROJECT_VERSION = ${buildNumber}
MAITRI_GIT_COMMIT = ${commit}
MAITRI_RELEASE_ID = ${releaseId}
`;

if (check) {
  // Verify the two generated artifacts describe the SAME release and that the
  // marketing version still matches package.json. The build number is not
  // re-derived here, so a check can run on a checkout without full git history.
  const problems = [];
  for (const path of [tsPath, xcPath]) {
    if (!existsSync(path)) problems.push(`missing ${path}`);
  }
  if (!problems.length) {
    const ts = readFileSync(tsPath, "utf8");
    const xc = readFileSync(xcPath, "utf8");
    const pick = (src, re, label) => {
      const m = src.match(re);
      if (!m) problems.push(`could not read ${label}`);
      return m?.[1];
    };
    const web = {
      version: pick(ts, /version: "([^"]+)"/, "web version"),
      build: pick(ts, /buildNumber: (\d+)/, "web build number"),
      commit: pick(ts, /commit: "([^"]+)"/, "web commit"),
      release: pick(ts, /releaseId: "([^"]+)"/, "web release id"),
    };
    const ios = {
      version: pick(xc, /MARKETING_VERSION = (\S+)/, "iOS MARKETING_VERSION"),
      build: pick(xc, /CURRENT_PROJECT_VERSION = (\d+)/, "iOS CURRENT_PROJECT_VERSION"),
      commit: pick(xc, /MAITRI_GIT_COMMIT = (\S+)/, "iOS commit"),
      release: pick(xc, /MAITRI_RELEASE_ID = (\S+)/, "iOS release id"),
    };
    for (const key of ["version", "build", "commit", "release"]) {
      if (web[key] !== ios[key]) {
        problems.push(`${key} differs — web: ${web[key]} / iOS: ${ios[key]}`);
      }
    }
    if (web.version !== version) {
      problems.push(`package.json version is ${version} but generated files say ${web.version}`);
    }
    if (web.release !== `${web.version}+${web.build}.${web.commit}`) {
      problems.push(`release id ${web.release} does not match its own parts`);
    }
    if (!problems.length) console.log(`[version] Web and iOS agree — ${web.release}`);
  }
  if (problems.length) {
    console.error(`[version] release metadata is not consistent:\n  - ${problems.join("\n  - ")}`);
    console.error("[version] run `bun run version:sync` and commit the result.");
    process.exit(1);
  }
  process.exit(0);
}

writeFileSync(tsPath, tsBody);
writeFileSync(xcPath, xcBody);
console.log(`[version] ${releaseId}`);
console.log(`[version] wrote src/lib/build-info.generated.ts + native/ios/version.xcconfig`);
